library(seqinr)
library(reshape2)
library(scales)
f1<-read.fasta(file="a.fasta", seqtype= "AA", as.string= T, strip.desc= T)
f2<-read.fasta(file="b.fasta", seqtype= "AA", as.string= T, strip.desc= T)
attr<-getAnnot(f1)
n<-length(f1)
out<-list()
for(i in 1:n) out[[i]]<-c(f1[[i]], f2[[i]])
write.fasta(sequences= out, names= attr, nbchar= 200, file.out= "concat_ab.fasta")
aln.mat<-as.matrix(read.alignment(file="concat_ab.fasta", format = "FASTA", forceToLower = F))
source(file="conditional mutual information.r")
x<-cmi(p,p1,p2)
cmi.r<-rescale(x, to=c(0,1))
write.csv(cmi.r, file="test_cmi.csv")
