library(seqinr)
library(reshape2)
library(scales)
library(dplyr)
f1<-read.fasta(file="a.fasta", seqtype= "AA", as.string= T, strip.desc= T)
f2<-read.fasta(file="a.fasta", seqtype= "AA", as.string= T, strip.desc= T)
attr<-getAnnot(f1)
out<-list()
n<-length(f1)
for(i in 1:n) out[[i]]<-c(f1[[i]], f2[[i]])
write.fasta(sequences= out, names= attr, nbchar= 200, file.out= "concat_a.fasta")
f1<-read.fasta(file="b.fasta", seqtype= "AA", as.string= T, strip.desc= T)
f2<-read.fasta(file="b.fasta", seqtype= "AA", as.string= T, strip.desc= T)
attr<-getAnnot(f1)
out<-list()
n<-length(f1)
for(i in 1:n) out[[i]]<-c(f1[[i]], f2[[i]])
write.fasta(sequences= out, names= attr, nbchar= 200, file.out= "concat_b.fasta")
source('conditional mutual information.r')
aln.mat<-as.matrix(read.alignment(file="concat_a.fasta", format= "FASTA", forceToLower = TRUE))
cmi_a<-cmi(p1+p1,p1,p1) ##p1= length of proteinA##
cmi_a<-rescale(cmi_a, to= c(0,1))
write.csv(cmi_a, file="test_cmi_a.csv")
cmi_a->m
m[upper.tri(m)] <- NA
ml<-melt(m, na.rm = TRUE)
ml$Var2<-gsub('V', '', ml$Var2)
ml$Var2<-as.integer(ml$Var2)
mls<-subset(ml, ml$Var1!=ml$Var2)
mlsx<-subset(mls, mls$Var1-mls$Var2>3)
top<-nrow(mlsx)*5/100
topr<-round(top[1])
final<-top_n(mlsx, topr)
final$Var1= paste0(final$Var1, 'A')
final$Var2= paste0(final$Var2, 'A')
write.csv(final, file="test_a_intra_top_5.csv")
aln.mat<-as.matrix(read.alignment(file="concat_b.fasta", format= "FASTA", forceToLower = TRUE))
cmi_b<-cmi(p2+p2,p2,p2) ##p2= length of proteinA##
cmi_b<-rescale(cmi_b, to= c(0,1))
write.csv(cmi_b, file="test_cmi_b.csv")
cmi_b->m
m[upper.tri(m)] <- NA
ml<-melt(m, na.rm = TRUE)
ml$Var2<-gsub('V', '', ml$Var2)
ml$Var2<-as.integer(ml$Var2)
mls<-subset(ml, ml$Var1!=ml$Var2)
mlsx<-subset(mls, mls$Var1-mls$Var2>3)
top<-nrow(mlsx)*5/100
topr<-round(top[1])
final<-top_n(mlsx, topr)
final<-top_n(mlsx, top)
final$Var1= paste0(final$Var1, 'B')
final$Var2= paste0(final$Var2, 'B')
write.csv(final, file="test_b_intra_top_5.csv")
